### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [ml-tooling/ml-workspace#103]
Hey there!

I belong to an open source security research community, and a member (@dig2) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by lukasmasuch** [comment]
@zidingz Thanks for reporting this security issue and reaching out to our mltooling.org email with further details. We will push a fix soon. 

I have added a [`SECURITY.md`](https://github.com/ml-tooling/ml-workspace/security/policy), feel free to give feedback on this policy :)

**Comment by JamieSlome** [comment]
@LukasMasuch - was the report a valid security issue, with a fix established? Just attaching the report for reference:

https://huntr.dev/bounties/d9d284fc-2a57-4f4a-abd9-6968d7342cf3/

It is private and only accessible to maintainers with repository write permissions! 👍
