### ISSUE TITLE
How to use gpu version with 11.0 nvidia-cuda version? 

### ISSUE THREAD

**Issue by anu7n** [ml-tooling/ml-workspace#105]
I am trying to use the gpu flavor but I have 11.0 nvidia version. Is there a way to downgrade the requirement on gpu flavor? If I can't do that, is there a way to add gpu on basic version of the ml-workspace? Thank you!

**Comment by sei-amellinger** [comment]
If you look at the Docker file in the gpu-flavor directory you could probably specify a different cuda base and roll your own.  It is a pretty easy thing to try and so worth the effort.

**Comment by anu7n** [comment]
Thank you for the support. I have solved the problem :)

**Comment by anu7n** [comment]
Thank you for the support. I have solved the problem :)
