### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Emporea** [ml-tooling/ml-workspace#107]
Can we expect updates anytime soon?
I really like to use ml-workspace. But since most of its software is outdated it becomes inconvinient to upgrade everything via pip / apt everytime I deploy a new container.

**Comment by MohamedElashri** [comment]
You can edit the `Dockerfile` with the updated versions of stuff (if a specific version is given) and then build the image. Then hopefully you will get updated version out of box. Unless some bugs occur with one of the updated libs/apps.

**Comment by raethlein** [comment]
Thanks for jumping in with the helpful advice @MohamedElashri to help out 🙂 
We have also started to update the libraries and tools [in this branch](https://github.com/ml-tooling/ml-workspace/tree/update-2022); the `light` and `minimal` versions are buildable with that and they look good so far. Next step is updating & building the full version (see the [runbook](https://github.com/ml-tooling/ml-workspace/blob/main/docs/update-workspace-image.md)). We will post an update here as soon as we have pushed the new images.

**Comment by dose-dot-dev** [comment]
@raethlein Do you intend to update either the R or Spark flavors as well? Definitely interested. Thank you for your work!

**Comment by sei-amellinger** [comment]
Does anyone here know how the tensorflow version is set?  I was thinking of seeing if I could update to 2.7. Is it part of the miniconda version?  (And ideally, I'd switch to miniforge.)

**Comment by sei-amellinger** [comment]
Can anyone provide on information as to if/when this will be addressed?

**Comment by rickdgit** [comment]
Up vote on this.
Is there any update recently ?
MlWorkspace is really a good tool for my usage

**Comment by Emporea** [comment]
You should just use [jupyterlab](https://github.com/jupyterlab/jupyterlab)  or [code-server](https://github.com/coder/code-server)  and install all extensions or libraries you need over there.

Its been too long since the last update that it might even represent secruity issues and you are missing out on new features because of old dependencies.

**Comment by MohamedElashri** [comment]
> You should just use [jupyterlab](https://github.com/jupyterlab/jupyterlab) or [code-server](https://github.com/coder/code-server) and install all extensions or libraries you need over there.
> 
> Its been too long since the last update that it might even represent secruity issues and you are missing out on new features because of old dependencies.

Better, you can update all tools and packages used in Dockerfile and keep using ml-workspace.

**Comment by Emporea** [comment]
But ml-workspace requires node 14.

Mind sharing your Dockerfile if you think its so easy to update every dependency?

**Comment by rickdgit** [comment]
> But ml-workspace requires node 14.
> 
> Mind sharing your Dockerfile if you think its so easy to update every dependency? 

I guess the docker file is [here](https://github.com/ml-tooling/ml-workspace/blob/main/Dockerfile) in their repo.
Im building my ubuntu test env soon and I will try rebuild this dockerfile to see if it is up to date
