### ISSUE TITLE
Image without Anaconda

### ISSUE THREAD

**Issue by lukas-a-olson** [ml-tooling/ml-workspace#108]
**Feature description:** Would it be possible to create a version of the image that does not use Anaconda?

**Problem and motivation:**

Since Anaconda changed their [Terms of Service](https://www.anaconda.com/terms-of-service), companies with more than 200 employees must purchase a license to use the Anaconda repo. My understanding is that this also prevents companies from using images like this that rely on that repo. I am hoping that we could make conda an optional part of the ML-Workspace to prevent conflicts with their ToS.

**Is this something you're interested in working on?**

No

**Comment by MohamedElashri** [comment]
In principle, I think yes. Also, this project uses Miniconda not anaconda. I'm not a lawyer, so I don't know if they have the same [restriction](https://www.anaconda.com/end-user-license-agreement-miniconda) exactly or not. If it does not, so you don't have to change anything.

**Comment by lukas-a-olson** [comment]
The Miniconda EULA links to the same Anaconda ToS that includes the language about commercial use. My understanding is that the restriction applies to any use Anaconda repository regardless of how it's accessed.
