### ISSUE TITLE
Kernel crashing on Apple M1 and Docker Desktop 4.5.0

### ISSUE THREAD

**Issue by arandi-software** [ml-tooling/ml-workspace#109]
**Describe the bug:**

Started the image and tried to import TF into a new notebook. Kernel keeps crashing and it tries to recover but crashes again.

Command executed:

import tensorflow as tf

tf.__version__

**Expected behaviour:**

Do not crash and run the code

**Steps to reproduce the issue:**

Install docker for Apple Silicon

Get latest version of ml-workspace

Start the instance

Open Browser (Safari or Chrome) and navigate to localhost:8080

Open existing notebook / create a new one 

Execute the following command:

import tensorflow as tf

tf.__version__

**Technical details:**

- Workspace version : 0.13.2
- Docker version : Docker Desktop for Apple M1 4.5.0, Engine Version: 20.10.12
- Host Machine OS (Windows/Linux/Mac): Mac 12.3
- Command used to start the workspace : docker run -p 8080:8080 --name "ml-workspace" --shm-size 512m mltooling/ml-workspace
- Browser (Chrome/Firefox/Safari): Chrome and Safari

**Possible Fix:**

**Additional context:**

**Comment by arandi-software** [comment]
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/1449213/158812310-66e230ad-fc29-44bc-ab6c-63146c3943f9.png">

**Comment by arandi-software** [comment]
17 12:51:31.766477: F tensorflow/core/lib/monitoring/sampler.cc:42] Check failed: bucket_limits_[i] > bucket_limits_[i - 1] (0 vs. 10)

qemu: uncaught target signal 6 (Aborted) - core dumped

kernel 1ac4f8b3-5b05-4197-b635-9b241185d73e restarted

**Comment by MohamedElashri** [comment]
You are using the ready docker image `mltooling/ml-workspace` which was built for `amd64` not `arm64` like M1. Docker on mac m1 is using QEMU to try to emulate things but not all things work correctly and even though you will get a serious performance hit. Until an ARM build is ready (it is not a simple build this on arm machine) you should rely more on amd64 machines.

**Comment by arandi-software** [comment]
OK. Thanks.
