### ISSUE TITLE
Set up unsuccessful

### ISSUE THREAD

**Issue by TimSYQQX** [ml-tooling/ml-workspace#12]
![image](https://user-images.githubusercontent.com/22300644/68078831-e5a13a00-fdb4-11e9-998e-7d39be21d848.png)
Any suggestions? Thanks

**Comment by lukasmasuch** [comment]
This looks like that there is a problem with permissions, which is preventing the supervisor process from starting those tool processes (jupyter, nginx...). This can happen if you have changed the root user to a different user (currently only the root user is supported, as explained in the FAQ section [here](https://github.com/ml-tooling/ml-workspace#faq)). Or maybe you have mounted a volume into the home directory or any directory other than /workspace. Do you have additional information on your setup, e.g., docker run command, cloud provider or local computer? Is there any other error within the logs that might be related to permissions?
