### ISSUE TITLE
XFCE4 Theme Customizations Not Persisting After Docker Container Restart

### ISSUE THREAD

**Issue by rocheston** [ml-tooling/ml-workspace#130]
**Description**
When I change my wallpaper, themes, icons, and other appearance settings, these customizations are lost after restarting the Docker container. The environment reverts to its original state, and none of my changes are saved.

**Steps to Reproduce**
1. Change the wallpaper, themes, icons, etc. in the appearance settings.
2. Restart the Docker container.
3. Notice that all customizations are reset to the default settings.

**Expected Behavior**
Customizations should persist after restarting the Docker container.

**Actual Behavior**
All customizations are lost after restarting the Docker container.

**Request for Help**
How can I customize the environment in such a way that these changes are saved and persist across container restarts?

**Comment by rocheston** [comment]
Ok, I figured this out. Thanks.

**Comment by DiegoZanella** [comment]
You should comment how you figured this out

**Comment by jerry3k** [comment]
Is this still upto date. Seems like last commit was 3 years ago?
