### ISSUE TITLE
I can‘t debug using vscode

### ISSUE THREAD

**Issue by moon290** [ml-tooling/ml-workspace#15]
**Describe the bug:**

when I use VSCODE，I can't debug.There is no reaction while I press the bottom.
Another question is that why I open vscode from VNC，debug is OK.
And when I open vscode from VNC,it's unable to recognize Chinese.
![20191119203617](https://user-images.githubusercontent.com/34809450/69147534-2b783500-0b0d-11ea-9628-10780eefd9ee.png)
![20191119204551](https://user-images.githubusercontent.com/34809450/69147698-96c20700-0b0d-11ea-99d2-3183c552ea02.png)

**Expected behaviour:**

**Steps to reproduce the issue:**

**Technical details:**

- Workspace version : 
- Docker version : 
- Host Machine OS (Windows/Linux/Mac): 
- Command used to start the workspace :
- Browser (Chrome/Firefox/Safari):

**Possible Fix:**

**Additional context:**

**Comment by lukasmasuch** [comment]
Python debugging within VS-Code should work now with the latest version of ML Workspace: `mltooling/ml-workspace:0.9.1`. If there is still an issue with the latest version, feel free to reopen the issue.
