### ISSUE TITLE
Support base url like jupyter NotebookApp.base_url

### ISSUE THREAD

**Issue by shawnz42** [ml-tooling/ml-workspace#16]
**Feature description:**
can support the docker env BASE_URL lile jupyter NotebookApp.base_url, so that the url will like http://$IP/$BASE_URL/tree?

**Problem and motivation:**
in the way, it can be deployed behind the nginx, the nginx conf can be written like this:
``` 
 location /$BASE_URL {
            proxy_pass http://$INNER_IP:8080;
        }
```
the user can use this url like `http://$NGINX_IP/$BASE_URL`  to visit the inner ml-workspace.

**Comment by lukasmasuch** [comment]
@zheya08 Thanks for your suggestion! We actually provide support for base url already with the `WORKSPACE_BASE_URL` environment variable. Just try something like:

```
docker run -p 8080:8080 --env WORKSPACE_BASE_URL=test mltooling/ml-workspace:latest
```

Does this work for you?

**Comment by shawnz42** [comment]
> @zheya08 Thanks for your suggestion! We actually provide support for base url already with the `WORKSPACE_BASE_URL` environment variable. Just try something like:
> 
> ```
> docker run -p 8080:8080 --env WORKSPACE_BASE_URL=test mltooling/ml-workspace:latest
> ```
> 
> Does this work for you?

It works! Thank you!
