### ISSUE TITLE
Updating vscode results in redirect

### ISSUE THREAD

**Issue by feribg** [ml-tooling/ml-workspace#17]
I updated vscode from it's UI  and now I always get  redirected to localhost/login which is not a valid URL, all the other tools work fine, but not VScode. Any ideas how to  debug or  reset it?

**Comment by raethlein** [comment]
Hey @feribg,

thanks for reporting the issue! We have just looked into the issue and it looks like one of the flags for code-server has changed.
For a quick fix, please try out following by executing the lines in your workspace's terminal:

```
sed -i "s/--no-auth/--auth none/g" /etc/supervisor/supervisord.conf
supervisorctl reload
```
It replaces the old flag with the new flag and restarts supervisor.
Afterwards, you should be able to access vscode again.

Please let us know whether this works for you!

**Comment by feribg** [comment]
Thanks, works! Required full restart of the container not just supervisor reload in case others are trying.

**Comment by raethlein** [comment]
Glad to hear that it works :)
