### ISSUE TITLE
Run other tools without exposing new ports

### ISSUE THREAD

**Issue by feribg** [ml-tooling/ml-workspace#19]
Wondering if there's an easy way to run other tools under port 8080, without exposing extra ports. For example Ray scheduler UI would listen on 8081?

For instance  the open port feature would generate a URL but  it can't be used  with something like Ray's UI (both of them share the query string  token)

http://172.17.0.2:8081/?token=c638fa7a06765f25408eefee6761091fd3716e7ae3fe177a

**Comment by lukasmasuch** [comment]
@feribg Only tools that either work on a relative URL or provide a way to set a base URL will work within the workspace (via access port feature). If the tool does not provide this, there is, unfortunately, no technical way to access it without opening another port. However, you can always use the browser within the VNC Desktop to access those tools (e.g. Ray's UI).
