### ISSUE TITLE
Pytorch Lightning as the backend

### ISSUE THREAD

**Issue by williamFalcon** [ml-tooling/ml-workspace#2]
Hi! check out Pytorch Lightning as an option for your backend!

https://github.com/williamFalcon/pytorch-lightning

**Describe the issue:**

**Technical details:**

- Workspace version : 
- Docker version : 
- Host Machine OS (Windows/Linux/Mac): 
- Command used to start the workspace :
- Browser (Chrome/Firefox/Safari):

**Comment by lukasmasuch** [comment]
@williamFalcon Thanks for your suggestion. We have added pytorch-lightning to the workspace and it is pre-installed in recent workspace versions.
