### ISSUE TITLE
Jupyter Notebook and Jupyter Lab seems to use only one CPU in multi-cpu configs

### ISSUE THREAD

**Issue by andr0idsensei** [ml-tooling/ml-workspace#20]
**Describe the bug:**

We have a setup where we have some cloud machines with one gpu and multiple cpus, which we use for training some models. In such a context, we've tried running our usual notebooks from the ml-workspace docker image with Jupyter Notebook as well as Jupyter Lab, however we've noticed that during training or multi-process operations, only one CPU on the machine is being used. We've noticed this in netstat as well as using htop.

**Expected behaviour:**

When running jupyter notebooks that use multiprocess operations, all cpus on the host machine should be used.

**Steps to reproduce the issue:**

Here is a piece of code we tried to run specifically to test this behaviour:
def f(x):
    while True:
        x*x
       
pool = multiprocessing.Pool(3)
pool.map(f,range(100))

**Technical details:**

- Workspace version : 0.8.7 
- Docker version : 18.09.7
- Host Machine OS (Windows/Linux/Mac): Ubuntu 18.04 LTS
- Command used to start the workspace : docker run -d -p 8081:8080 --name "ml-workspace" -v ${WORKSPACE_DIR}:/workspace -v /data/:/data --runtime nvidia --env NVIDIA_VISIBLE_DEVICES="all" --env AUTHENTICATE_VIA_JUPYTER="token" --shm-size 512m --restart always $IMAGE
- Browser (Chrome/Firefox/Safari):

**Possible Fix:**

Our suspicion is that maybe there are some restrictions in the setup/run config for Jupyter Notebook.

**Additional context:**

**Comment by lukasmasuch** [comment]
@andr0idsensei I just did some evaluation on different machines with your code, but was not able to replicate the issue (atleast with the current build version of workspace: `mltooling/ml-workspace:0.9.0-SNAPSHOT`). 

For example, here I tried your code within JupyterLab with two different Pool sizes and both seem to be able to use the available CPUs.

<img width="933" alt="Screenshot at Jan 29 10-19-27" src="https://user-images.githubusercontent.com/2852129/73343849-910d3e00-4281-11ea-88b8-b39b00e42218.png">

Have you checked if other Docker containers have access to the full count of CPUs (maybe the Docker daemon has some limiting configuration)? Have you used a CPU limit on the workspace container?

**Comment by lukasmasuch** [comment]
Closing this issue for now since it does not seem to be happening with the latest workspace version. Feel free to reopen the issue if you can still replicate it with the latest version.

**Comment by andr0idsensei** [comment]
Thanks Lukas. I haven't checked with the latest version, but I found that it was caused by setting thread affinity via the KMP_AFFINITY env variable. For me it worked if I set the value to empty.

**Comment by lukasmasuch** [comment]
@andr0idsensei Thanks, thats very valuable feedback. The `KMP` settings where adapted from the recommendations of Intel: https://software.intel.com/en-us/articles/maximize-tensorflow-performance-on-cpu-considerations-and-recommendations-for-inference

Unfortunately, I don't have a deep understanding of how `KMP_AFFINITY` works, but it seems like that for some hardware setups this setting does not actually optimize the performance.

**Comment by lukasmasuch** [comment]
I'm a bit confused that the `KMP_AFFINITY` actually has an effect on the python multiprocessing module. I don't think that the multiprocessing module actually uses any `OpenMP` code.

**Comment by andr0idsensei** [comment]
Actually, I think that we might have messed up the initial multiprocess test somehow, and multiprocessing may not be affected by that (we haven't re-tested that though). The fact that you mentioned for you the bug was not reproducible, made me think a bit more about this. What we actually noticed was that when we used FastAI and Pytorch to train some models, that we usually trained on a multi-cpu and multi-gpu rig, using ml-workspace training was slower and not all CPU's were used. We tried to replicate that with the Pool example in the initial bug report, and at first it seemed to reproduce. However I think, I tried it once before finding out about KMP_AFFINITY, and I couldn't reproduce it. Since I don't think FastAI and Pytorch use multiprocessing (also haven't verified that) it would make sense that they were affected by KMP_AFFINITY.

**Comment by qixing-ai** [comment]
i have the same bug 
you can find it just by:
1. !stress -c 10
2. import torch
3. !stress -c 10
step1 show out 100% of 10 cpu
step3 show out 10% of 10 cpu

and i find that bug only in jupyter notebook. 

docker version is 20
ml version is last

and its fine by:

import os
os.environ ['KMP_AFFINITY'] = ''
