### ISSUE TITLE
Ungit is not loading in the browser 

### ISSUE THREAD

**Issue by IslamAlam** [ml-tooling/ml-workspace#21]
**Describe the bug:**
The Ungit link, from the workspace "Open Tool", is not loading the web interface for the Ungit.
![ezgif com-add-text](https://user-images.githubusercontent.com/4381819/71491745-d8438180-2832-11ea-8489-56c58a5fddae.gif)

**Expected behaviour:**
Open the web interface for Ungit

**Steps to reproduce the issue:**
Open the ML-Hub login to the server.
2. Create a new server with a given name
3. After the server spawn, access the server.
4. Open Tool -> Ungit 

**Technical details:**

- Workspace version : 0.8.7
- Docker version : 
- Host Machine OS (Windows/Linux/Mac): Linux
- Command used to start the workspace :  ML-Hub 
- Browser (Chrome/Firefox/Safari): Chrome, Firefox

**Possible Fix:**

**Additional context:**

**Comment by IslamAlam** [comment]
The problem was the port mapping between Ungit port and the Nginx port.

**Comment by lukasmasuch** [comment]
@IslamAlam Do you have more information on the port mapping problem. Is it related the the OpenResty/Nginx fix you introduced in the Pull Request?

**Comment by IslamAlam** [comment]
@LukasMasuch I had this issue with the latest docker workspace image from docker. I am using as well the ml-hub to provide access to multiple users.
When I use the image alone with docker, there is no issue with Ungit, but when the server is spawn via ML-Hub, the Ungit is not accessible anymore.

**Comment by lukasmasuch** [comment]
@IslamAlam Does this issue still happen with the `mltooling/ml-workspace:0.9.1` image? Ungit within the newest image is working fine for me with the newest version of ML Hub, however, I have just tested with Docker for now (not via Kubernetes).

**Comment by IslamAlam** [comment]
@LukasMasuch After testing this image, the problem still persists. All tools work without issue except Ungit.

It is working within the VNC from the local port but cannot be accessed from the tools menu. 

![image](https://user-images.githubusercontent.com/4381819/73399082-ec254c00-42e6-11ea-83e4-a6fd14c9b8ab.png)

![image](https://user-images.githubusercontent.com/4381819/73398843-79b46c00-42e6-11ea-8c9f-b16a33966ed9.png)

**Comment by lukasmasuch** [comment]
Thanks for the information. Seems like a problem with the proxy of ML Hub. To replicate the issue, I would need to know:
- Which ML Hub version are you using?
- Is ML Hub deployed on Kubernetes or Docker?

**Comment by IslamAlam** [comment]
@LukasMasuch I have tested the issue further during the last couple of day. It is not related to ML Hub, it is an issue with traefik. 
It is not able to handle the URL of Ungit. I was not able to understand why or how to fix it.

**Comment by lukasmasuch** [comment]
@IslamAlam Thanks for investigating 👍 I think the issue either needs to be fixed with traefik or with Ungit, we probably cannot really do anything to fix this issue within the workspace. If you find out more information why this happens, feel free to post it here.

**Comment by alexjj** [comment]
@IslamAlam did you find a solution? I have the same issue but it's more widespread (all apps have the same response and kernels won't connect. This is all via traefik over the public internet. If I connect via local IP to my server at home it all works just fine.

**Comment by IslamAlam** [comment]
@alexjj what is the traefik' labels which you are using for the container of the ml-workspace?

This is my currnet setup which works with all apps except Ungit. My feeling is the # is the problematic character in the Ungit url path.

    labels:
        traefik.docker.network: web
        traefik.enable: "true"
        traefik.http.middlewares.ml-workspace-https-redirect.redirectscheme.scheme: https
        traefik.http.routers.ml-workspace-secure.entrypoints: web-secure
        traefik.http.routers.ml-workspace-secure.rule: Host(`***.***.***`)
        traefik.http.routers.ml-workspace-secure.service: ml-workspace
        traefik.http.routers.ml-workspace-secure.tls: "true"
        traefik.http.routers.ml-workspace-secure.tls.certresolver: default
        traefik.http.routers.ml-workspace.entrypoints: web
        traefik.http.routers.ml-workspace.middlewares: ml-workspace-https-redirect
        traefik.http.routers.ml-workspace.rule: Host(`***.***.***``)
        traefik.http.services.ml-workspace.loadbalancer.server.port: '8000'

**Comment by alexjj** [comment]
I'm still using traefik 1.7 so the old style. I had to add the `passHostHeader` and make a websockets entry point (wss) in my `traefik.toml` otherwise jupyter couldn't connect to the kernel. Ungit still doesn't work. Most other things do. 

```
    labels:
      - "traefik.backend=mlworkspace"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:ml.domain.com"
      - "traefik.docker.network=web"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https,wss"
```
