### ISSUE TITLE
can ml-workspace be easily deployed on Kubernetes ? 

### ISSUE THREAD

**Issue by yuanbw** [ml-tooling/ml-workspace#23]
It would be great if ml-workspace can be easily deployed on Kubernetes through helm or yaml scripts, and  can expose metrics  to promethues and grafana.

**Comment by ggliem** [comment]
Have you checked out [MLHub](https://github.com/ml-tooling/ml-hub) and the corresponding [Kubernetes/Helm deployment repo](https://github.com/ml-tooling/zero-to-mlhub-k8s) based on Zero to JupyterHub?

**Comment by skurfuerst** [comment]
FYI: MLhub works really well on Kubernetes for me :heart:
