### ISSUE TITLE
Tensorboard run faile in GPU image

### ISSUE THREAD

**Issue by RaydonLiu** [ml-tooling/ml-workspace#26]
when I run an ml-workspace GPU container, jupyter_tensorboard raise error ' Invalid response: 500 Internal Server Error'. And when I run tensorboard on a terminal, it raises error 'ValueError: Duplicate plugins for name projector'. So how can I fix this problem?

**Comment by lukasmasuch** [comment]
@RaydonLiu Thanks for reporting this issue. It will be fixed in the upcoming release. You can already try it here: `mltooling/ml-workspace-gpu:0.9.0-SNAPSHOT`. The new stable version will be released in the next few days.
