### ISSUE TITLE
File Browser runs as root

### ISSUE THREAD

**Issue by jax79sg** [ml-tooling/ml-workspace#27]
The file browser opens up without authentication (By typing link in browser directly) and runs as root. This pose a serious security issue.

**Comment by lukasmasuch** [comment]
The file browser is secured via the `AUTHENTICATE_VIA_JUPYTER` token (as any other tool hosted within the workspace). If you call the link in your browser, it is using the cookies to authenticate you as a user. You can try to open the same link using incognito mode in your browser or after cleaning your cookies and you should get the following message: `You are not allowed to access the filebrowser via the provided token.` In case you have set the `AUTHENTICATE_VIA_JUPYTER` token and it is still logging you in within the incognito mode, then there actually is a security issue which we need to investigate.

**Comment by lukasmasuch** [comment]
Feel free to reopen the issue in case you can replicate the issue with the latest version: `mltooling/ml-workspace:0.9.1` and by using a token via the `AUTHENTICATE_VIA_JUPYTER` environment variable.
