### ISSUE TITLE
JupyterLab Terminal Error

### ISSUE THREAD

**Issue by martineastwood** [ml-tooling/ml-workspace#3]
**Describe the bug:**
Jupyterlab terminal fails to open from Launcher screen with error message `i is not a constructor`. Also, trying to start a terminal in Jupyterlab by selecting file->new->terminal fails to open a new terminal tab

**Expected behaviour:**
A new terminal tab should be opened in Jupyterlab

**Steps to reproduce the issue:**
1. Run `docker run -p 8080:8080 mltooling/ml-workspace:latest`
2. Navigate to http://localhost:8080
3. Select `Open Tool`, `Jupyterlab`
4. From Jupyterlab's Lancher screen click on `Terminal` icon
<img width="733" alt="Screen Shot 2019-09-23 at 12 28 30" src="https://user-images.githubusercontent.com/8270216/65422464-7839db00-ddfe-11e9-8d8c-f0353bfc6738.png">

**Technical details:**

- Workspace version : 0.8.4
- Docker version :
Client: Docker Engine Community:
 Version:	18.09.2
 API version:	1.39
 Go version:	go1.10.8
 Git commit:	6247962
 Built:	Sun Feb 10 04:12:39 2019
 OS/Arch:	darwin/amd64
Experimental:	false

Server Docker Engine Community:
 Engine:
  Version:	18.09.2
  API version:	1.39 (minimum version 1.12)
  Go version:	go1.10.6
  Git commit:	6247962
  Built:	Sun Feb 10 04:13:06 2019
  OS/Arch:	linux/amd64
  Experimental:	true
- Host Machine OS (Windows/Linux/Mac): MacOS Mojave 10.14.6
- Command used to start the workspace : docker run -p 8080:8080 mltooling/ml-workspace:latest
- Browser (Chrome/Firefox/Safari): Chrome 75.0.3770.142 (Official Build) (64-bit)

**Possible Fix:**

**Additional context:**
Using Safari as browser gives the error message `undefined is not a constructor (evaluating 'new i(s,n)')`

**Comment by lukasmasuch** [comment]
Thanks @martineastwood for reporting this issue! I was also able to reproduce the error. It seems like a bug with Jupyterlab version `1.1.3`. I will fix it in the next workspace version by updating Jupyterlab to `1.1.4`. 

As a quickfix, you can just update jupyterlab within the running workspace (using the Jupyter terminal): 

```python
conda install -y -c conda-forge jupyterlab=1.1.4
```

**Comment by martineastwood** [comment]
Thanks @LukasMasuch, I can confirm the quickfix above works. Looking forward to the next version with the fix :)

**Comment by lukasmasuch** [comment]
I just uploaded a new Workspace version (`0.8.5`) to Dockerhub which contains a fix for the terminal problem with JupyterLab. While upgrading JupyterLab makes the terminal functional again, the actual problem was with some incompatible JupyterLab extensions. You can try it out via:
```bash
docker run -p 8080:8080 mltooling/ml-workspace:0.8.5
```

**Comment by nrasadi** [comment]
I have the same problem with JupyterLab version `3.1.10` on Ubuntu 17.10.
The error's title is `Launcher Error`, and the message is `Unhandled error`.
