### ISSUE TITLE
exited: nginx (terminated by SIGILL (core dumped); not expected)

### ISSUE THREAD

**Issue by MyMakibox** [ml-tooling/ml-workspace#30]
Awesome project that I am using to make ML available to students.

Picked up this issue:

After following docs, cannot access webservices, log shows

exited: nginx (terminated by SIGILL (core dumped); not expected)

- Docker version 19.03.5
- Host Machine OS Linux: 
- Command used to start the workspace : docker run -d \
    -p 8080:8080 \
    --name "ml-workspace" -v "${PWD}:/workspace" \
    --env AUTHENTICATE_VIA_JUPYTER="mytoken" \
    --shm-size 512m \
    --restart always \
    mltooling/ml-workspace:latest

**Possible Fix:**

This is likely the same issue described here:
https://github.com/docksal/service-vhost-proxy/issues/35
https://github.com/metwork-framework/mfext/issues/384

Running on older hardware means no SSE4.2.

It would be great if this can be worked around so that older hardware can be used by students to access current tools. ML-Tooling already helps a lot when connecting to a remote server, which is great. This issue prevents running the container locally. Alternatively, SSE4.2 should be mentioned as a hardware requirement, or tested for in the container with appropriate logging.

**Comment by lukasmasuch** [comment]
@MyMakibox Thanks for reporting this issue and your investigation! Indeed, this looks like a problem with the binaries of OpenResty, which do no support some older processors (see https://github.com/openresty/openresty/issues/267#issuecomment-309296900). Theoretically, we might solve this by building the workspace (and OpenResty) on a computer with an older CPU. But this will most likely be quite a challenge. Do you have more information on what kind of CPU you have in your hardware and how old it is?

**Comment by MyMakibox** [comment]
@LukasMasuch The specific laptop shows /proc/cpuinfo:
 Intel(R) Core(TM)2 Duo CPU     T5450  @ 1.66GHz

While it was on its way to scrap, it works very well with ubuntu and a browser connected to a PC hosting ML-Workspace.

**Comment by lukasmasuch** [comment]
@MyMakibox I added a short description about this issue to the Known Issues section (see [develop branch](https://github.com/ml-tooling/ml-workspace/tree/develop#known-issues)). Unfortunately, fixing this might be too much effort as of now. If more people encounter the problem, we will do some more evaluation on if and how to provide a fix.

**Comment by YuanZhencai** [comment]
I have the same problem

**Comment by chrisamow** [comment]
Same problem here on an old eight core i7 (old but not nearly as old as the OP):
processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 30
model name	: Intel(R) Core(TM) i7 CPU         870  @ 2.93GHz
stepping	: 5
microcode	: 0xa
cpu MHz		: 1226.167
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida flush_l1d
vmx flags	: vnmi preemption_timer invvpid ept_x_only flexpriority tsc_offset vtpr mtf vapic ept vpid
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit
bogomips	: 5851.68
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
