### ISSUE TITLE
Was able to build the Dockerfile but it wont Run

### ISSUE THREAD

**Issue by ml-developer24** [ml-tooling/ml-workspace#31]
Hi i was able to build the Dockerfile by commenting out all the jupyter extensions. However i am not able to run the image for some reason. I get the following saying all of the add ons have entered a running state. 
![Screen Shot 2020-02-14 at 10 52 55 AM](https://user-images.githubusercontent.com/61063149/74559051-56113880-4f18-11ea-84fa-ec218372bdaf.png)

**Comment by lukasmasuch** [comment]
@ml-developer24 This actually looks as expected. Make sure that you have opened the `8080` port in your docker run command (`-p 8080:8080`) and then visit: http://localhost:8080

**Comment by ml-developer24** [comment]
Thank you.... i wanted to comment out some of the tools and just want ungit and netdata as the tools on the drop down.... could you help identify which sections of the dockerfile refer plainly to installing ungit and nedata

**Comment by lukasmasuch** [comment]
While you certainly can remove most other tool installations from the Dockerfile directly, I would not recommend for doing this. It takes a lot of work, effort, and time to modifying and building the full workspace image. Instead, it is a lot more convenient to extend from the workspace image and remove selected tools from the drop down and prevent selected tools from starting. Here is an exemplary Dockerfile that demonstrates how to prevent most other tools from starting and removes all tool links other than netdata and ungit:

```dockerfile
FROM mltooling/ml-workspace:0.9.1

# Prevent unneeded tools from starting:
RUN \
    rm /etc/supervisor/conf.d/filebrowser.conf && \
    rm /etc/supervisor/conf.d/glances.conf && \
    rm /etc/supervisor/conf.d/novnc.conf && \
    rm /etc/supervisor/conf.d/sshd.conf && \
    rm /etc/supervisor/conf.d/vncserver.conf && \
    rm /etc/supervisor/conf.d/vscode.conf && \
    rm /etc/supervisor/conf.d/xrdp.conf

# Remove unneeded tools from dropdown:
RUN \
    rm $HOME/.workspace/tools/01-novnc.json && \
    rm $HOME/.workspace/tools/03-jupyterlab.json && \
    rm $HOME/.workspace/tools/04-vscode.json && \
    rm $HOME/.workspace/tools/05-terminal.json && \
    rm $HOME/.workspace/tools/07-glances.json && \
    rm $HOME/.workspace/tools/08-filebrowser.json && \
    rm $HOME/.workspace/tools/09-access-port.json && \
    rm $HOME/.workspace/tools/10-ssh-access.json && \
    rm $HOME/.workspace/tools/11-install-tool.json
```

After building the image (`docker build -t my-workspace:latest .`) and running it (`docker run -p 8080:8080 my-workspace:latest`) you will see that only ungit and netdata are available in the dropdown:

![image](https://user-images.githubusercontent.com/2852129/74566131-13c91500-4f73-11ea-8c6f-35e58195f54f.png)
