### ISSUE TITLE
Notebooks as tile instead of tree

### ISSUE THREAD

**Issue by vagarwal77** [ml-tooling/ml-workspace#36]
For Jupyter labs, I have a specific requirement - Instead of showing multiple notebooks as a tree view, i would like to show all the notebooks as in the TILE view as attached. 

Please suggest of Jupyter Labs has any existing extension to achieve the same? 

I searched a lot but could not figured it out!!

<img width="1619" alt="Screen Shot 2020-03-09 at 6 34 11 PM" src="https://user-images.githubusercontent.com/46463536/76263470-58c02e80-6235-11ea-938c-dd6ffb567e31.png">

**Comment by cgddrd** [comment]
@vagarwal77 - why have you labelled this as a bug? This seems to be a feature request to me?

**Comment by lukasmasuch** [comment]
@vagarwal77 Sorry, I'm unaware of any extension that provides this tile view. And we currently do not plan to implement such a view.
