### ISSUE TITLE
Cannot find generated token for authentication in the container logs

### ISSUE THREAD

**Issue by vrodriguezf** [ml-tooling/ml-workspace#37]
Hi,

According to the README, in the Authentication section: "You can also use <generated> to let Jupyter generate a random token that is printed out on the container logs."

I am trying to execute:
```
docker run -p 8080:8080 --env AUTHENTICATE_VIA_JUPYTER="<generated>" mltooling/ml-workspace:latest
``` 

but I cannot find any token in the logs produced by the command `docker logs`.

Where is that generated token logged?

Thanks!

**Comment by alexMyG** [comment]
You can list the notebooks running within the container by running:

`docker exec -it <NAME_OF_CONTAINER> jupyter notebook list`

You will see the token at the end of the URL of your notebook.

**Comment by vrodriguezf** [comment]
got it, thanks!
