### ISSUE TITLE
Dependency upgrade: GPflow -> 2.0, TensorFlow -> 2.1

### ISSUE THREAD

**Issue by st--** [ml-tooling/ml-workspace#38]
Hi! Looks like a great all-in-one tool that you're building :)

Unfortunately, the version of GPflow you are pinning, 1.5.1 (see https://github.com/ml-tooling/ml-workspace/blob/master/resources/libraries/requirements-full.txt - same in develop branch) is out of date, and doesn't work with the also-pinned tensorflow 2.x. I would have simply opened a pull request on that file, but it looks like it is autogenerated and it is not clear to me how to change that. Also, GPflow requires TensorFlow 2.1 (which contains numerous bugfixes over TensorFlow 2.0, for example fixed memory leaks). What if anything could I do to help you upgrade the dependencies and bring ml-workspace up to date?

**Comment by st--** [comment]
@LukasMasuch hi I looked at #56 and it seems to just remove GPflow entirely - was that intentional ? If so, would you be willing to explain your motivation for that? (It looks like you bumped TensorFlow to 2.3, with which GPflow 2.1 should be fully compatible.)

**Comment by lukasmasuch** [comment]
@st-- I think there was a problem, but I can't remember anymore. It installs without any problem with the current version, so I added it again (https://github.com/ml-tooling/ml-workspace/commit/48a77ef9e3e6ee2f21ad5ec5bb24f3655019f1ca). GPflow will be included again in the next release.
