### ISSUE TITLE
Can I deploy it on offline machine?

### ISSUE THREAD

**Issue by tcqiuyu** [ml-tooling/ml-workspace#39]
**Describe the issue:**

I have a server that does not allow external internet connection. So it is not applicable to download docker image from hub. I wondered whether ml-workspace offers an offline deployment? Thanks in advance.
**Technical details:**

- Workspace version : 
- Docker version : 
- Host Machine OS (Windows/Linux/Mac): 
- Command used to start the workspace :
- Browser (Chrome/Firefox/Safari):

**Comment by MutedPermit** [comment]
I think it could be possible but a little bit hard to achieve.
If you manage to install docker on your server you can get the docker image from a machine with access to internet and then pass it to the server machine as a file.
For this you can do something like in the machine with internet:
```shell
docker pull mltooling/ml-workspace:latest
docker save -o ml-workspace mltooling/ml-workspace:latest
```
And the pass the file to your server (USB, for example..) and then
```shell
docker load -i ml-workspace
docker run -p 8080:8080 ml-workspace
```
However, you have to be aware that some features wouldn't work without internet connection: for example, git or installing libraries.

Hope it helps :)

**Comment by lukasmasuch** [comment]
Closing this issue since @MutedPermit provided the best available solution for installing ml-workspace on an offline machine.
