### ISSUE TITLE
Passing JavaScript objects to the IPython kernel isn't possible with JupyterLab

### ISSUE THREAD

**Issue by se-jaeger** [ml-tooling/ml-workspace#4]
**Describe your request:**

If JupyterLab is used it isn't possible to passing JavaScript objects to the IPython kernel. This is described in the _Jupyter Tipps & Tricks_ tutorial section _4.6  Run Javascript_. I added some information   (#5 ) but it's maybe a good idea to add this information also to a more general area to avoid nasty behaviors/bugs.

**Which page or section is this issue related to?**

Using `docker run -p 8080:8080 mltooling/ml-workspace:latest` the corresponding section is at: **http://localhost:8080/notebooks/tutorials/jupyter-tipps.ipynb#Run-Javascript**

**Comment by lukasmasuch** [comment]
Thanks for the suggestion. I have merged the PR. I will most likely also add something to the Readme (e.g., in known problems section) later. I will keep the issue open for now.
