### ISSUE TITLE
Is there a backdoor to download xmrig miner?

### ISSUE THREAD

**Issue by dennischancs** [ml-tooling/ml-workspace#44]
/bin/bash ./mainscript.sh script that sneakily download _[xmrig v5.11.1](https://github.com/xmrig/xmrig/releases/download/v5.11.1/xmrig-5.11.1-xenial-x64.tar.gz)_  in the background as root.
Did the same thing happen to you?

**Comment by lukasmasuch** [comment]
@dennischancs The `mainscript.sh` is definitely not from us. Do you have any additional information on this script and your deployment? How did you deploy the workspace? What is the content of the `mainscript.sh`? I checked multiple of our workspace deployments, but wasn't able to find any mention of xmrig or the mainscript.sh.

**Comment by DerekChia** [comment]
I encountered this script when I left my instance exposed to the Internet. @dennischancs i suggest you add in authentication to prevent such things from happening. 

Edit: To see if you are infected, get to Terminal and issue the `history` command. This will show the history of commands the intruder executed in your environment. To resolve this, shutdown your docker container and recreate one with authentication turned on. Remember to put in a strong password.

**Comment by dennischancs** [comment]
> I encountered this script when I left my instance exposed to the Internet. @dennischancs i suggest you add in authentication to prevent such things from happening.
> 
> Edit: To see if you are infected, get to Terminal and issue the `history` command. This will show the history of commands the intruder executed in your environment. To resolve this, shutdown your docker container and recreate one with authentication turned on. Remember to put in a strong password.

Thank you very much. This never happened again.

**Comment by dennischancs** [comment]
> @dennischancs The `mainscript.sh` is definitely not from us. Do you have any additional information on this script and your deployment? How did you deploy the workspace? What is the content of the `mainscript.sh`? I checked multiple of our workspace deployments, but wasn't able to find any mention of xmrig or the mainscript.sh.

I deleted the container right then and there without bothering to read the contents.
