### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by Emporea** [ml-tooling/ml-workspace#48]
Hello, just wanted to ask if one can expect that this repository will get updates in the future or if it got abonded?

I use the jupyter labs and vscode on a daily basis but each of their own received a lot of updates since the last half year or so and ml-tooling hasnt had any updates since january.

Is it because of corona?

**Comment by deanp70** [comment]
Hey @Emporea, not sure if this is still relevant to you, but I tried reaching out to the maintainers and didn't get a response, so I created a fork and updated most of the packages. You can find it here, and I would welcome PR, requests if you have any: https://github.com/dagshub/ml-workspace

BTW, the updated containers themselves on Docker Hub are here: 
- https://hub.docker.com/repository/docker/dagshub/ml-workspace-minimal
- https://hub.docker.com/repository/docker/dagshub/ml-workspace

**Comment by raethlein** [comment]
Hey @Emporea and @deanp70 , thanks for the question and great to hear about your efforts to update the packages! 
Due to a variety of reasons like working on Corona projects and other work-related things, we were unfortunately not able to be very active here. We plan to become more active again and update the repositories and go through the issues very soon! Just Friday, we released a cool repository in the context of our work - and leveraging the ml-workspace repository - which you can find [here](https://github.com/sap/machine-learning-lab/).

@deanp70 Would you mind to create a PR with your changes so we can have a look and probably be able to merge them?
Edit: I have just seen that there is a PR already open with regards to package updates. Maybe there is an overlap.

**Comment by cgddrd** [comment]
Super thrilled to see this project coming back @raethlein!

**Comment by deanp70** [comment]
> Hey @Emporea and @deanp70 , thanks for the question and great to hear about your efforts to update the packages!
> Due to a variety of reasons like working on Corona projects and other work-related things, we were unfortunately not able to be very active here. We plan to become more active again and update the repositories and go through the issues very soon! Just Friday, we released a cool repository in the context of our work - and leveraging the ml-workspace repository - which you can find [here](https://github.com/sap/machine-learning-lab/).
> 
> @deanp70 Would you mind to create a PR with your changes so we can have a look and probably be able to merge them?
> Edit: I have just seen that there is a PR already open with regards to package updates. Maybe there is an overlap.

Indeed I mainly merged that commit and made sure everything still works. Great to hear you will look at the PR.

**Comment by Emporea** [comment]
Yeah I would really welcome a continuation of this repository!

**Comment by raethlein** [comment]
We have just merged in the PR with the updates 🙂

**Comment by allenzhao** [comment]
@raethlein Shall we expect a new version so we can update our docker images? Thanks!

**Comment by raethlein** [comment]
@allenzhao Yes, we are working on a new version :) Unfortunately, I cannot tell the exact date but we should be able to release it in November

**Comment by westurner** [comment]
How many minutes does a build w/ GitHub Actions take?
- https://www.docker.com/blog/docker-github-actions/
- https://github.com/marketplace/actions/build-and-push-docker-images (by docker)

**Comment by raethlein** [comment]
@westurner We have created a GitHub Actions to build the repository. So far, I have just tested building the minimal flavor locally via [act](https://github.com/nektos/act), but I have just triggered a GitHub Actions run in this repo (for the minimal version first to see whether it runs through). So, we shall soon know :)

**Comment by raethlein** [comment]
@westurner The build takes around 70 minutes. Though I don’t know yet whether that fluctuates between different runs.
