### ISSUE TITLE
We can't debug in vscode.

### ISSUE THREAD

**Issue by moon290** [ml-tooling/ml-workspace#49]
when we use vscode(http://localhost:8080/tools/vscode/), there is no reaction if we debug. But using vscode in VNC, it's ok.

**Comment by deanp70** [comment]
@moon290 This seems like a VScode version issue. It works on the up to date version. I created a [fork here](https://github.com/dagshub/ml-workspace) and updated the relevant tools if you want to use it. Not sure what language you're writing it, but debugging in Python now works.

**Comment by raethlein** [comment]
Thanks to the two of you for reporting this and offering a solution! After merging PR #46 Python debugging works also now with this workspace (right now you have to build it locally to use it but we will push a new image version soon)
