### ISSUE TITLE
RStudio Graphics Device Error

### ISSUE THREAD

**Issue by martineastwood** [ml-tooling/ml-workspace#6]
**Describe the bug:**
Cannot plot charts in RStudio due to graphics device error

**Expected behaviour:**
Charts should appear in RStudio's Viewer panel

**Steps to reproduce the issue:**
- docker run -p 8080:8080 mltooling/ml-workspace-r:latest
- Open Rstudio
- Load Iris dataset and plot chart as shown in screenshot below
- 
![Screen Shot 2019-10-01 at 08 12 44](https://user-images.githubusercontent.com/8270216/65941569-4ab6e800-e423-11e9-9092-dc74f85151b6.png)

**Technical details:**
- Workspace version : 0.8.5 : 
- Docker version : Docker version :
Client: Docker Engine Community:
Version: 18.09.2
API version: 1.39
Go version: go1.10.8
Git commit: 6247962
Built: Sun Feb 10 04:12:39 2019
OS/Arch: darwin/amd64
Experimental: false

Server Docker Engine Community:
Engine:
Version: 18.09.2
API version: 1.39 (minimum version 1.12)
Go version: go1.10.6
Git commit: 6247962
Built: Sun Feb 10 04:13:06 2019
OS/Arch: linux/amd64
Experimental: true

- Host Machine OS (Windows/Linux/Mac): MacOS Mojave 10.14.6
- Command used to start the workspace :docker run -p 8080:8080 mltooling/ml-workspace-r:latest
- Browser (Chrome/Firefox/Safari): Chrome 75.0.3770.142 (Official Build) (64-bit)

**Possible Fix:**
You may need to install Cairo in the Docker image before RStudio - https://stackoverflow.com/questions/19513705/error-in-rstudiogd-shadow-graphics-device-error-r-error-4-r-code-execution

**Additional context:**

**Comment by lukasmasuch** [comment]
Thanks @martineastwood. I uploaded a new workspace image containing a fix for this problem (version 0.8.6):
```bash
docker run -p 8080:8080 mltooling/ml-workspace-r:0.8.6
```

![image](https://user-images.githubusercontent.com/2852129/65980069-bd04e800-e476-11e9-9109-b6ad27e1337d.png)

Does it work for you as well?

**Comment by martineastwood** [comment]
Thank you @LukasMasuch, I can confirm it is working for me now too.
![Screen Shot 2019-10-02 at 08 10 04](https://user-images.githubusercontent.com/8270216/66024596-270ba480-e4ec-11e9-901a-d3e4b88e7064.png)
