### ISSUE TITLE
i want to change browser port

### ISSUE THREAD

**Issue by Foreist** [ml-tooling/ml-workspace#61]
ml-workspace If you click filebrowser in the right tool, i can connect to port 0000. Can you change the default port?
It's troublesome to change one by one

**Comment by lukasmasuch** [comment]
@Foreist you can set the default workspace port via the `WORKSPACE_PORT` environment variable. However, we do not recommend changing this default port. Does this answer your question?

**Comment by Foreist** [comment]
Good
