### ISSUE TITLE
404 for extension pydeck

### ISSUE THREAD

**Issue by allenzhao** [ml-tooling/ml-workspace#62]
**Describe the bug:**

When opening up a new notebook, using developer tools in Chrome shows 404 error for this path: /nbextensions/widgets/notebook/js/extension.js
and
/nbextensions/pydeck/extension.js

**Expected behaviour:**

Loads the js files successfully

**Steps to reproduce the issue:**
Create a new notebook, open developer tools in Chrome, console shows the 404 error.

**Technical details:**

- Workspace version : 0.11.0
- Docker version : 19.03.8
- Host Machine OS (Windows/Linux/Mac): Linux
- Command used to start the workspace : docker run -d \
    -p 8080:8080 \
    --name "gpu-workspace" -v "${PWD}:/workspace" \
    --env AUTHENTICATE_VIA_JUPYTER="PASSWORD" \
    --shm-size 32g \
    --restart always \
    --gpus all \
    mltooling/ml-workspace-gpu:latest
- Browser (Chrome/Firefox/Safari): Chrome

**Possible Fix:**
Reinstall the extension in next build?

**Additional context:**

**Comment by lukasmasuch** [comment]
@allenzhao Thanks for reporting this issue. I have deactivated the pydeck extension for the next release. If there is interest in the pydeck extension, I can also try to figure out the root cause of the problem.
