### ISSUE TITLE
404 pop up when the folder name contains notebooks

### ISSUE THREAD

**Issue by allenzhao** [ml-tooling/ml-workspace#63]
**Describe the bug:**

When the folder name contains notebooks, seems [this line of code](https://github.com/ml-tooling/ml-workspace/blob/fa0c5390b2dfc9f7c343453d4e8333d0a0ec338b/resources/jupyter/extensions/tooling-extension/jupyter_tooling/tooling-shared-components.js#L9) will cause two unexpected popup, showing 404 as a result. 

See image:
![image](https://user-images.githubusercontent.com/3326332/103081971-b512f580-459e-11eb-8d5f-47be3c91b55c.png)

Console says js tried to load tooling/tools and tooling/storage/check after the baseURL was reconginized as the current full url, which caused the bug.
**Expected behaviour:**
Works fine without the popup.

**Steps to reproduce the issue:**
1. Create a folder named notebooks
2. Create a notebook
3. Two popups shows errors

**Technical details:**

- Workspace version : 
- Docker version : 
- Host Machine OS (Windows/Linux/Mac): 
- Command used to start the workspace :
- Browser (Chrome/Firefox/Safari):

**Possible Fix:**
A better way of the regex?

**Additional context:**
I discovered this and thought it was related to #62 at first, and was somehow caused by the pydeck extension. Then later I found out that it was actually a different bug ;)

**Comment by lukasmasuch** [comment]
@allenzhao Good catch, thanks! I already changed the regex a few days ago (https://github.com/ml-tooling/ml-workspace/commit/fa0c5390b2dfc9f7c343453d4e8333d0a0ec338b) :) But I will need to test if this fixes the mentioned problem.

**Comment by lukasmasuch** [comment]
@allenzhao This issue should be fixed in the new release: https://github.com/ml-tooling/ml-workspace/tree/v0.12.1
