### ISSUE TITLE
JupyterLab 3.0

### ISSUE THREAD

**Issue by sim-san** [ml-tooling/ml-workspace#64]
**Feature description:**

The new major release of the [JupyterLab 3.0 is released!](https://blog.jupyter.org/jupyterlab-3-0-is-out-4f58385e25bb) 

**Problem and motivation:**

The new version has more functionalities:  [Visual Debugger](https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#visual-debugger) and a lot of other features and bugfixes

Here is the migration guide: [JupyterLab 2.x to 3.x](https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html#jupyterlab-2-x-to-3-x)

**Is this something you're interested in working on?**

No

**Comment by lukasmasuch** [comment]
Hey @sim-san, thanks for notifying us :) I just took a look at JupyterLab 3.0. I will update it once a few more extensions are compatible with JupyterLab 3. You can follow the progress in this issue: https://github.com/jupyterlab/jupyterlab/issues/9461
