### ISSUE TITLE
vscode, vnc, ungit, rstudio permission problem

### ISSUE THREAD

**Issue by Foreist** [ml-tooling/ml-workspace#65]
**Feature description:**

vscode, vnc, ungit, rstudio proceeds without password

**Problem and motivation:**

we can escape the risk of hacking.

**Is this something you're interested in working on?**

Can I set a password?

**Comment by lukasmasuch** [comment]
@Foreist if you set a password as explained in the [Enable Authentication](https://github.com/ml-tooling/ml-workspace#enable-authentication) section in the docs (e.g. via `AUTHENTICATE_VIA_JUPYTER`), all tools (including vscode, vnc, ungit, rstudio, ...) will be protected with this password. So, it is a single login giving you access to all tools in the workspace. Does this answer your question?

**Comment by Foreist** [comment]
@LukasMasuch
No, my docker code is:
`docker run --name "??" -d --runtime nvidia --gpus '"device=1"' -p ?:8080 -p ?:8787 -p ?:8071 -e LC_ALL=C.UTF-8 -v /home/:/workspace -e USER=? -e PASSWORD=? --env AUTHENTICATE_VIA_JUPYTER=? dxodnd/ml-workspace-gpu-python-rstudio:tagname`

Same as above.
However, all tools can access without any authentication procedure.
password and authenticate-via-jupyter is same
plz save me(jupyter notebook, lab require authentication)

![image](https://user-images.githubusercontent.com/46616734/103900894-b9611600-513b-11eb-87c4-cf850a61da3f.png)

![image](https://user-images.githubusercontent.com/46616734/103905442-f4fede80-5141-11eb-90b5-5e9b1bbb9b19.png)

**Comment by lukasmasuch** [comment]
@Foreist looks fine for me. VS code and other tools do not need additional authentication since they are secured by the Jupyter token as well using the same session and cookie. You can try to access VS Code in a different browser or in incognito mode. You will be denied access and forwarded to the Jupyter login screen (so no unauthenticated login possible).

**Comment by lukasmasuch** [comment]
Important for security is that you only expose the `8080` port and access all tools through this port.

**Comment by Foreist** [comment]
@LukasMasuch 
looks fine for me?...
I can access vscode just by address without entering any password.
right today, due to this issue, virtual currency was mined on the server.
Do you think you entered the password like the screen above and showed the screen below?
I didn't enter my password, I just changed the address.
Except for jupyter notebook and lab, all access is possible without authentication.

**Comment by lukasmasuch** [comment]
@Foreist 

To help you with the issue, I need a few more information from you:

1. Which internal port are you using to access vs-code, `8080` with the `/tools/vscode` path? Which is the address you use to access vs-code? 
2. Which workspace version is the `dxodnd/ml-workspace-gpu-python-rstudio:tagname` image based on?
3. What are the other ports you are exposing: `8787` and `8071`? 
4. Can you also reproduce the problem with the docker images provided by us, e.g: 

> I just tried it with the current version and wasn't able to reproduce the issue. 

```
docker run \
    -p 8080:8080 \
    --env AUTHENTICATE_VIA_JUPYTER="mytoken" \
    mltooling/ml-workspace:0.11.0
```

5. `virtual currency was mined on the server` do you have more information on that, maybe there is any security issue I'm not aware of? Was there a mining script running inside the workspace?

**Comment by Foreist** [comment]
@LukasMasuch 
1. 1030 port, if me enter """https:???:1030/tools/vscode/""" in the address bar, you can connect without authentication.

2. It is a gpu-flavor installed in the past. I erased the version, so I can't remember.

3. Another port is additionally required to interface with the rstudio server.
I was able to use rstudio by running r-runtime.sh and r-studio-server.sh in gpu-favor.
But since I didn't use r-flavor, I couldn't start by clicking on rstudio in open tools.
So rstudio only ran when I ran it with a command like 
terminal:
LD_LIBRARY_PATH="" LD_PRELOAD="" USER=1008 /usr/lib/rstudio-server/bin/rserver --server-working-dir=/workspace/1008/.Rprofile --server-daemonize=0 --auth-none=1 --auth-validate-users=0 --www-port 8071

However, due to issues like rstudio's permissions, the folder won't be created properly or the files won't be created unless you grant permissions with the shmod 777 command.

I would like to hear some advice.

4. Running the code you presented solves the authentication problem.
However, if you install r via r-runtime.sh and r-studio-server.sh in a container created this way,
I think you are getting the rstudio permission problem mentioned in 3.
I hope for help.

5. Is there a backdoor to download xmrig miner? #44 a is an issue of the this git that has been mentioned in the past.
I think it's the same case.

**Comment by lukasmasuch** [comment]
3. I think this is solvable for a new version, maybe it would be good if you create a new issue specifically for this issue with r-studio.
4. I would suggest that we focus on fixing the issue with r-studio-server (with a new issue) so that you can use the newest workspace version where the authentication problem is not present. 
5. I did some investigation back then but could find any hint that any aspect of the workspace is compromised. Therefore, it's very important for me to collect as much information as possible on this issue. The workspace itself is checked by virus and vulnerabilities scans for every new version release. I assumed that the issue might occur when the workspace / or jupyter is started without any authentication. How did you discovered that crypto was mined on your server?

**Comment by Foreist** [comment]
It was slow, so when I ran htop I noticed that the server slowed down with the same problem as #44.
And a user named rstudio uploaded xmrig.zip to the server.(Default ID given to rstudio when installing r-flavor)
rstudio can also be accessed without authentication in the old version of mlworkspace.
First of all, I have confirmed that there are no authentication problems in the latest version.
If you are still experiencing this problem after version 0.11.0, it would be a good idea to investigate this a bit more.
Please let me know if you have any questions about me.
For me, mlworkspace makes data science life easy and fun 👍 
Thank you for always.

**Comment by Foreist** [comment]
To build a gpu and rstudio environment, is it the fastest to use r-runtime.sh and r-studio-server.sh in gpu-flavor?
It would be nice to create a new issue, but I struggled for 7 hours due to security issues.
Please help me a little too~

**Comment by lukasmasuch** [comment]
@Foreist If you just need r-runtime and r-studio-server in one running workspace container, you can start the `mltooling/ml-workspace-gpu:0.11.0` version and run the `r-runtime.sh` and the `r-studio-server.sh` script. In case you want to have a docker image where the `gpu` stuff and `r` is preinstalled, you can adapt the [r-workspace dockerfile](https://github.com/ml-tooling/ml-workspace/blob/main/r-flavor/Dockerfile) and use the GPU-workspace as base-image. I will try test this for you today or tomorrow and maybe even provide a gpu + r image as well.

**Comment by Foreist** [comment]
ok, I just ran into another problem that way, but now I think it's a good idea to move the issue.

**Comment by lukasmasuch** [comment]
@Foreist there is now also an experimental `gpu-r` flavor (https://hub.docker.com/repository/docker/mltooling/ml-workspace-gpu-r) which combines the existing `gpu` and the `r` flavors. If you try it, feel free to give us some feedback if it works for you. Unfortunately, I wasn't able to test this image myself yet.

**Comment by Foreist** [comment]
@LukasMasuch 
ok, I'll try it and contact you :)
