### ISSUE TITLE
rstudio port related problem 

### ISSUE THREAD

**Issue by Foreist** [ml-tooling/ml-workspace#66]
**Describe your request:**

**Which page or section is this issue related to?**
May be associated with #65(Rstudio)

Currently, running rstudio install via r-runtime.sh and rstudio-server.sh has a small problem.

For example, suppose you visit the port with -p 1000:8080 -p 1001:8000 in docker.
8080 will be connected with jupyter.
When I install rstudio-server via sh I run into problems.
If you start rstudio server with `LD_LIBRARY_PATH="" LD_PRELOAD="" USER=rstudio /usr/lib/rstudio-server/bin/rserver --server-working-dir=/workspace/rstudio/.Rprofile --server-daemonize=0 --auth-none=1 --auth-validate-users=0 --www-port 8000`, you can connect to rstudio through domain.com:1000/tools/1001 and domain.com:1001.
The former requires authentication, while the latter does not.
In this case, it is recommended to connect www-port to a port independent of the server.(ex: 12000)
Maybe it's still because I'm new to mlworkspace.
beginners will need to be careful when using mlworkspace.
It would be nice if this part was written in document
thx.

**Comment by raethlein** [comment]
Hey @Foreist, thanks for highlighting this. Indeed, the workspace should not publish any other port than 8080. It is built in a way that the tools inside are all accessible over this port and, as a result, require authentication. In your example, you should not publish port 1001 in the first place, but if you do, it is in your responsibility to secure it. I think your suggestion to make this more clear in the documentation makes a lot of sense, so we will add a note to the Section [Access Ports](https://github.com/ml-tooling/ml-workspace#access-ports) or to the [FAQs](https://github.com/ml-tooling/ml-workspace#faq).

**Comment by Foreist** [comment]
I love mlworkspace!
