### ISSUE TITLE
Data Loss when closing docker

### ISSUE THREAD

**Issue by minhson-kaist** [ml-tooling/ml-workspace#82]
I closed the jupyter notebook GUI and start it again, and all of my data disappeared. Are there any reasons for that?

**Comment by raethlein** [comment]
Hey @detuvoldo, could you show the Docker command that you used to start the workspace, please? And could you also elaborate a little bit more on the "closed the jupyter notebook GUI" part? Do you mean removing the container or killing the process or closing the browser window or something like that?

**Comment by minhson-kaist** [comment]
I simply use the command for GPU flavor `docker run -p 8080:8080 --gpus all mltooling/ml-workspace-gpu:0.12.1`.
I use `Ctrl+C` to kill the process and start the image again. Then, all the data I uploaded to this image disappear.

**Comment by raethlein** [comment]
> ... and start the image again

Do you mean executing the command `docker run -p 8080:8080 --gpus all mltooling/ml-workspace-gpu:0.12.1` again or to start the exited container again via `docker start $container_id` (where `$container_id` refers to the id of the exited container which you get, for example, via `docker ps -a`?
When restarting the same container, all data should actually be persisted.
Though, maybe our [persist-data section](https://github.com/ml-tooling/ml-workspace#persist-data)
helps.

**Comment by minhson-kaist** [comment]
Oh thanks for pointing it out. I found my problems.
