### ISSUE TITLE
Stuck in "Loading: Just wait a minute, some setups are going on in the background ..."

### ISSUE THREAD

**Issue by seraphkz** [ml-tooling/ml-workspace#84]
**Describe the issue:**

I spun up a container, everything seems to have gone well (see command below), but when I visited on my browser, I keep getting "Just wait a minute, some setups are going on in the background ..."

**Technical details:**

- Workspace version : 
- Docker version : 20.10.6 
- Host Machine OS (Windows/Linux/Mac): Ubuntu
- Command used to start the workspace :
docker run -d -p 8080:8080 --name "ml-workspace" -v "data:/workspace" --env AUTHENTICATE_VIA_JUPYTER="F3t72051089" --shm-size 512m  --restart always  mltooling/ml-workspace:0.12.1

- Browser (Chrome/Firefox/Safari): Chrome

**Comment by lukasmasuch** [comment]
@seraphkz Seems like that the Jupyter server did not start correctly, but I haven't seen the problem with this version before. Can you share the container logs as well? This would help a lot in finding out the problem.

**Comment by samgj18** [comment]
qemu: uncaught target signal 6 (Aborted) - core dumped

2021-05-20 05:45:25,355 INFO exited: jupyter (terminated by SIGABRT; not expected)

2021/05/20 05:45:25 [error] 377#0: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8090/", host: "localhost:8080", referrer:
