### ISSUE TITLE
Unable to get tigervnc when building the image

### ISSUE THREAD

**Issue by ericksantillanp** [ml-tooling/ml-workspace#85]
**Describe the bug:**
By building the image from scratch it seems that this package is no longer in https://dl.bintray.com/tigervnc/stable/tigervnc-1.11.0.x86_64.tar.gz :

https://github.com/ml-tooling/ml-workspace/blob/91a3cea2e1597474bf71707b5636d4c640898e67/Dockerfile#L430

Here are the logs after a docker build . 
```
#25 3.462 Fetched 22.5 MB in 3s (7,158 kB/s)
#25 3.462 Reading package lists...
#25 4.828 
#25 4.828 gzip: stdin: unexpected end of file
#25 4.829 tar: Child returned status 1
#25 4.829 tar: Error is not recoverable: exiting now
------
executor failed running [/bin/sh -c apt-get update  &&     cd ${RESOURCES_PATH} &&     wget -qO- https://dl.bintray.com/tigervnc/stable/tigervnc-1.11.0.x86_64.tar.gz | tar xz --strip 1 -C / &&     mkdir -p ./novnc/utils/websockify &&     wget -qO- https://github.com/novnc/noVNC/archive/v1.2.0.tar.gz | tar xz --strip 1 -C ./novnc &&     wget -qO- https://github.com/novnc/websockify/archive/v0.9.0.tar.gz | tar xz --strip 1 -C ./novnc/utils/websockify &&     chmod +x -v ./novnc/utils/*.sh &&     mkdir -p $HOME/.vnc &&     fix-permissions.sh ${RESOURCES_PATH} &&     clean-layer.sh]: exit code: 2
```

**Steps to reproduce the issue:**

` docker build . `

**Technical details:**

- Workspace version : 
- Docker version : 
- Host Machine OS (Windows/Linux/Mac): 
- Command used to start the workspace :
- Browser (Chrome/Firefox/Safari):

**Possible Fix:**

I think this is the new place: https://sourceforge.net/projects/tigervnc/files/stable/1.11.0/tigervnc-1.11.0.x86_64.tar.gz/download

**Additional context:**

**Comment by raethlein** [comment]
Hey @ericksantillanp, thanks for the update! In case the newer vnc version does not start in the workspace, have a look at [this commit](https://github.com/ml-tooling/ml-workspace/commit/28b4f962e6d82f5d4ca9d850f6dad63abcc2f981) (in that branch we are working on a version for Ubuntu 20.04).
