### ISSUE TITLE
Build of spark flavor with new version 0.13.2

### ISSUE THREAD

**Issue by marianobilli** [ml-tooling/ml-workspace#98]
Thanks for releasing new version 0.13.2, would it be possible you build the spark flavor in docker hub using this new base flavor?
Thanks!

**Comment by lukasmasuch** [comment]
@marianobilli I'm happy to see people using the spark flavor :) I  assumed a low usage and excluded it from the update to save some time. I will try to find some time to provide an update for the spark image as well.

**Comment by marianobilli** [comment]
Honestly the spark flavor is a bit heavy, it would be good if it is based on the minimal-flavor and not on top of the r-flavor.

But we are using it a lot, by replacing the spark client with the custom aws spark client and connecting it to AWS EMR clusters.

**Comment by amouhsine** [comment]
I don't know @marianobilli  I would still like to have it on top of R. I am using the current 0.12 versio because of it :)

**Comment by marianobilli** [comment]
Sure no problem, we are using it anyway, so @LukasMasuch do you think you could build the image? thanks!

**Comment by marianobilli** [comment]
I would still be happy if this build can happen :)

**Comment by sim-san** [comment]
I would like to try out the new Spark 3.2 on our ml-hub

**Comment by sim-san** [comment]
Still interested

**Comment by marianobilli** [comment]
march 2022 still interested! @LukasMasuch

**Comment by dose-dot-dev** [comment]
also interested!

**Comment by rickdgit** [comment]
Still interested @LukasMasuch
